### ISSUE TITLE
Does not work in forge

### ISSUE THREAD

**Issue by AlmightyAnubis** [Rubyboat1207/howmany#2]
I tried using the mod in forge 1.20.1 but there doesn't pop anything up. Is there any keybind I am missing?

PS.: Would be nice if you mention the Architectury API dependency in your modrinth project.

**Comment by Rubyboat1207** [comment]
Yes, apologies! The keybind is L, just press it over any slot in your inventory.

This is my first time making an Architectury mod, and it doesnt use any of the api features, so ill remove the dependency on the mod itself
